### ISSUE TITLE
Project Goal: Wheel of Date Night

### ISSUE THREAD

**Issue by jakelipscomb** [esbev/project-1-collab#3]
AS A user
I WANT to click a button
SO THAT I will be given options on a genre for a movie with suggestions on what to watch
AND I will be given options for a food cuisine with suggestions on a meal for the occasion

**Comment by akecs512** [comment]
How about
AS A user I will be given options for movie genres and food cuisines
WHEN i click a button
I will be given a pairing of movie and cuisine 
THEN I will be presented with  a list of options for each category.
